#!/usr/local/bin/php
<?php

use App\Command\CreateDatabase;

if (php_sapi_name() !== 'cli') {
    exit;
}

require dirname(__DIR__).'/../vendor/autoload.php';

if($argv[1] == 'create-database') {
	$dbCreator = new CreateDatabase();
	$dbCreator->createTables();
	echo 'done';
} else {
	echo 'command not found';
}